### ISSUE TITLE
hint dialog error

### ISSUE THREAD

**Issue by Yasin00006** [champred/UPR-Android#10]
You can no longer bring up the hint dialog by tapping on the text labels of the settings in v0.3.6a, when you click on a text label an empty dialog box appears and disappears in an instant.

**Comment by champred** [comment]
Thank you for the report. Not sure what happened. Will need to investigate further.

**Comment by champred** [comment]
I rewrote the code to how it should have been in the first place. Originally I had done it a much weirder way that was completely unnecessary. [Please try the new release.](https://github.com/champred/UPR-Android/releases/tag/v0.3.7)
