### ISSUE TITLE
Generation 1 Pokemon Romd

### ISSUE THREAD

**Issue by Ruttsu17** [champred/UPR-Android#4]
What do you do if you want to randomize a Generation 1 rom like Red, Blue or Yellow?

**Comment by champred** [comment]
RBY strings are built-in presets as of 76e1ca1bd511212fa7ec095e22ffaa7d0389a0b4

**Comment by champred** [comment]
Once you load a gen 1 ROM (Red, Blue, or Yellow) it will show a list of presets to choose from like it the image below:
![](https://user-images.githubusercontent.com/46391895/258672516-99715796-76a2-4ac5-8355-05f8e7f61cdd.png)

You can of course also customize your own settings if you would like.

**Comment by Ruttsu17** [comment]
I keep trying to load a rom of Pokemon Yellow onto the Randomizer but,
after i do the app just closes down

**Comment by champred** [comment]
Thank you for letting me know. I think it is because Yellow has one less starter than the other games. I will work on a fix ASAP.

**Comment by champred** [comment]
Should be fixed by 79da039c3cecf5a7dc96d0ee7c1d688f2dcb69da. Will publish a new release within the next day or so.

**Comment by champred** [comment]
New release is now live. [Please try it here.](https://github.com/champred/UPR-Android/releases/tag/v0.3.6a)

**Comment by Ruttsu17** [comment]
Thank you

**Comment by champred** [comment]
You're welcome! Let me know if you experience any other issues since I don't have a Yellow ROM to test with.
